default_data_source_fetch_method = "ctx.data_unchecked::<DataSource>()"
enum_rename_items = "camelCase"

header = "use async_graphql::*; use crate::web::graphql::DataSource;"

# we have no interfaces nor unions
phases = ["objects", "input_objects", "scalars", "enums"]

[[enum]]
target_enum = "TransactionSortByInput"
rename_items = "SCREAMING_SNAKE_CASE"

[[enum]]
target_enum = "StakeSortByInput"
rename_items = "SCREAMING_SNAKE_CASE"

[[enum]]
target_enum = "BlockSortByInput"
rename_items = "SCREAMING_SNAKE_CASE"

[[enum]]
target_enum = "FeetransferSortByInput"
rename_items = "SCREAMING_SNAKE_CASE"

[[enum]]
target_enum = "NextstakeSortByInput"
rename_items = "SCREAMING_SNAKE_CASE"

[[enum]]
target_enum = "SnarkSortByInput"
rename_items = "SCREAMING_SNAKE_CASE"

[[resolver]]
target_type = "Query"
target_field = "type"

[[resolver]]
target_type = "Transaction"
target_field = "block"
resolver_type = "field"

[[resolver]]
target_type = "Transaction"
target_field = "receiver"
resolver_type = "field"

[[resolver]]
target_type = "Block"
target_field = "protocolState"
resolver_type = "field"

[[resolver]]
target_type = "BlockProtocolState"
target_field = "blockchainState"
resolver_type = "field"

[[resolver]]
target_type = "BlockProtocolState"
target_field = "consensusState"
resolver_type = "field"

[[resolver]]
target_type = "BlockProtocolStateConsensusState"
target_field = "stakingEpochData"
resolver_type = "field"

[[resolver]]
target_type = "BlockProtocolStateConsensusState"
target_field = "nextEpochData"
resolver_type = "field"

[[resolver]]
target_type = "BlockProtocolStateConsensusStateStakingEpochDatum"
target_field = "ledger"
resolver_type = "field"

[[resolver]]
target_type = "BlockProtocolStateConsensusStateNextEpochDatum"
target_field = "ledger"
resolver_type = "field"

[[resolver]]
target_type = "Block"
target_field = "snarkJobs"
resolver_type = "field"

[[resolver]]
target_type = "Block"
target_field = "transactions"
resolver_type = "field"

[[resolver]]
target_type = "Block"
target_field = "winnerAccount"
resolver_type = "field"

[[resolver]]
target_type = "Block"
target_field = "creatorAccount"
resolver_type = "field"

[[resolver]]
target_type = "Block"
target_field = "snarkJobs"
resolver_type = "field"

[[resolver]]
target_type = "BlockTransaction"
target_field = "coinbaseReceiverAccount"
resolver_type = "field"

[[resolver]]
target_type = "BlockTransaction"
target_field = "feeTransfer"
resolver_type = "field"

[[resolver]]
target_type = "BlockTransaction"
target_field = "userCommands"
resolver_type = "field"

[[resolver]]
target_type = "BlockTransactionUserCommand"
target_field = "feePayer"
resolver_type = "field"

[[resolver]]
target_type = "BlockTransactionUserCommand"
target_field = "fromAccount"
resolver_type = "field"

[[resolver]]
target_type = "BlockTransactionUserCommand"
target_field = "receiver"
resolver_type = "field"

[[resolver]]
target_type = "BlockTransactionUserCommand"
target_field = "source"
resolver_type = "field"

[[resolver]]
target_type = "BlockTransactionUserCommand"
target_field = "toAccount"
resolver_type = "field"

[[resolver]]
target_type = "BlockWinnerAccount"
target_field = "balance"
resolver_type = "field"

[[resolver]]
target_type = "Feetransfer"
target_field = "blockStateHash"
resolver_type = "field"

[[resolver]]
target_type = "Snark"
target_field = "block"
resolver_type = "field"

[[resolver]]
target_type = "Stake"
target_field = "delegationTotals"
resolver_type = "field"

[[resolver]]
target_type = "Stake"
target_field = "permissions"
resolver_type = "field"

[[resolver]]
target_type = "Stake"
target_field = "timing"
resolver_type = "field"

[[resolver]]
target_type = "Nextstake"
target_field = "nextDelegationTotals"
resolver_type = "field"

[[resolver]]
target_type = "Nextstake"
target_field = "permissions"
resolver_type = "field"

[[resolver]]
target_type = "Nextstake"
target_field = "timing"
resolver_type = "field"
